### ISSUE TITLE
[python3.7 ]  5-10頁 堪誤回報

### ISSUE THREAD

**Issue by 841020** [JustinSDK/Python37Tutorial#1]
python35-32 應修正為python37-32
![81217255_1790704284399936_2667041551124791296_n](https://user-images.githubusercontent.com/33141341/71760958-0fcfbf00-2f00-11ea-8ae4-57d062465ab2.jpg)

**Comment by JustinSDK** [comment]
已列入堪誤，感謝！
https://github.com/JustinSDK/Python37Tutorial/blob/master/errata.md
