### ISSUE TITLE
[python3.7 ] 第八章 堪誤回報

### ISSUE THREAD

**Issue by 841020** [JustinSDK/Python37Tutorial#2]
![IMG_1844](https://user-images.githubusercontent.com/33141341/75691670-54e55700-5cdf-11ea-889c-5b49b87de9ce.JPG)
此處應該是指同時進行讀取與寫入

![IMG_1843](https://user-images.githubusercontent.com/33141341/75691787-7f371480-5cdf-11ea-8cef-d1f960b0ad7c.JPG)
此處應該是指標準輸入或輸出

**Comment by JustinSDK** [comment]
已加入堪誤，感謝！
